
import { CharacterProfile } from '../../types';

export interface Preset {
  name: string;
  profile: CharacterProfile;
}

export const PRESETS: Preset[] = [
  {
    name: 'Нана',
    profile: {
      gender: 'Женский',
      age: 28,
      bust: 105,
      waist: 68,
      hips: 115,
      height: 172,
      weight: 70,
      hairLength: 'Очень длинные',
      hairType: 'Спиральные',
      hairstyle: 'Косы',
      hairColor: 'Брюнет',
      eyeColor: 'Карие',
      hasMakeup: true,
      eyelinerStyle: 'Крылая',
      eyeshadowColor: 'Нейтральный коричневый',
      lipstickColor: 'Глянцевый розовый',
      skinTone: 'Темная',
      ethnicity: 'Африканский',
      imageStyle: 'Гиперреалистичная фотография',
      physiqueDescription: '',
      bodyFat: 30,
      muscleMass: 'Мягкая',
      breastShape: 'Круглая',
      breastFirmness: 'Мягкая',
      buttockShape: 'Круглая',
      buttockFirmness: 'Мягкая',
      headShape: 'Круглая',
      foreheadSize: 'Средний',
      eyebrowShape: 'Дугообразные',
      eyebrowThickness: 'Густые',
      eyeShape: 'Круглые',
      eyeSize: 'Большие',
      eyeSpacing: 'Среднее расстояние',
      noseShape: 'Широкий',
      noseSize: 'Средний',
      lipShape: 'Полные',
      cheekbones: 'Полные щеки',
      chinShape: 'Круглый',
      clothingPreset: 'Белое бикини',
      baseLayerType: 'Нет одежды',
      baseLayerColor: '',
      baseLayerMaterial: 'Обычная ткань',
      topType: 'Верх от бикини',
      topColor: 'Белый',
      topMaterial: 'Обычная ткань',
      bottomType: 'Низ от бикини',
      bottomColor: 'Белый',
      bottomMaterial: 'Обычная ткань',
      outerwearType: 'Нет одежды',
      outerwearColor: '',
      outerwearMaterial: 'Обычная ткань',
      footwearType: 'Сандалии',
      footwearColor: 'Белый',
      footwearMaterial: 'Обычная ткань',
      accessories: ['Серьги-кольца'],
      accessoriesCustom: 'Большие золотые серьги-кольца',
      hasAccessories: true,
      hasTattoos: false,
      tattooDescription: '',
    }
  },
  {
    name: 'Эльфийский Рейнджер',
    profile: {
      gender: 'Женский',
      age: 125,
      bust: 85,
      waist: 60,
      hips: 90,
      height: 180,
      weight: 65,
      hairLength: 'Очень длинные',
      hairType: 'Прямые',
      hairstyle: 'Косы',
      hairColor: 'Серебряный',
      eyeColor: 'Зеленые',
      hasMakeup: false,
      eyelinerStyle: 'Нет',
      eyeshadowColor: 'Нет',
      lipstickColor: 'Нет',
      skinTone: 'Светлая',
      ethnicity: 'Европеоид',
      imageStyle: 'Фэнтези-арт (воздушный)',
      physiqueDescription: '',
      bodyFat: 18,
      muscleMass: 'Атлетическая',
      breastShape: 'Атлетическая',
      breastFirmness: 'Упругая',
      buttockShape: 'Круглая',
      buttockFirmness: 'Тонизированная',
      headShape: 'Сердцевидная',
      foreheadSize: 'Средний',
      eyebrowShape: 'Изогнутые',
      eyebrowThickness: 'Средние',
      eyeShape: 'Миндалевидные',
      eyeSize: 'Большие',
      eyeSpacing: 'Среднее расстояние',
      noseShape: 'Прямой',
      noseSize: 'Маленький',
      lipShape: 'Тонкие',
      cheekbones: 'Высокие скулы',
      chinShape: 'Острый',
      clothingPreset: 'Эльфийский Рейнджер',
      baseLayerType: 'Нет одежды',
      baseLayerColor: '',
      baseLayerMaterial: 'Обычная ткань',
      topType: 'Туника',
      topColor: 'Темно-зеленый',
      topMaterial: 'Обычная ткань',
      bottomType: 'Леггинсы',
      bottomColor: 'Коричневый',
      bottomMaterial: 'Обычная ткань',
      outerwearType: 'Плащ',
      outerwearColor: 'Темно-зеленый',
      outerwearMaterial: 'Обычная ткань',
      footwearType: 'Ботинки',
      footwearColor: 'Коричневый',
      footwearMaterial: 'Обычная ткань',
      accessories: [],
      accessoriesCustom: 'Потертая кожаная броня поверх туники',
      hasAccessories: true,
      hasTattoos: false,
      tattooDescription: '',
    }
  },
  {
    name: 'Киберпанк Нетраннер',
    profile: {
      gender: 'Женский',
      age: 22,
      bust: 80,
      waist: 62,
      hips: 85,
      height: 175,
      weight: 58,
      hairLength: 'Короткие',
      hairType: 'Прямые',
      hairstyle: 'Ирокез',
      hairColor: 'Электрический синий',
      eyeColor: 'Фиолетовые',
      hasMakeup: true,
      eyelinerStyle: 'Кошачий глаз',
      eyeshadowColor: 'Сливовый фиолетовый',
      lipstickColor: 'Глубокий ягодный',
      skinTone: 'Бледная',
      ethnicity: 'Восточноазиатский',
      imageStyle: 'Киберпанк (неоновый нуар)',
      physiqueDescription: '',
      bodyFat: 20,
      muscleMass: 'Тонизированная',
      breastShape: 'Стройная',
      breastFirmness: 'Упругая',
      buttockShape: 'Квадратная',
      buttockFirmness: 'Упругая',
      headShape: 'Квадратная',
      foreheadSize: 'Средний',
      eyebrowShape: 'Прямые',
      eyebrowThickness: 'Тонкие',
      eyeShape: 'Монолитное веко',
      eyeSize: 'Средние',
      eyeSpacing: 'Среднее расстояние',
      noseShape: 'Нос-кнопка',
      noseSize: 'Маленький',
      lipShape: 'В форме сердца',
      cheekbones: 'Высокие скулы',
      chinShape: 'Острый',
      clothingPreset: 'Киберпанк Нетраннер',
      baseLayerType: 'Нет одежды',
      baseLayerColor: '',
      baseLayerMaterial: 'Обычная ткань',
      topType: 'Рубашка на пуговицах',
      topColor: 'Черный',
      topMaterial: 'Обычная ткань',
      bottomType: 'Брюки',
      bottomColor: 'Черный',
      bottomMaterial: 'Обычная ткань',
      outerwearType: 'Куртка',
      outerwearColor: 'Черный',
      outerwearMaterial: 'Обычная ткань',
      footwearType: 'Ботинки',
      footwearColor: 'Черный',
      footwearMaterial: 'Обычная ткань',
      accessories: [],
      accessoriesCustom: 'Сетчатая рубашка под курткой, куртка с неоново-синими акцентами, тактические штаны, высокотехнологичные ботинки',
      hasAccessories: true,
      hasTattoos: false,
      tattooDescription: '',
    }
  },
  {
    name: 'Студент Университета',
    profile: {
      gender: 'Мужской',
      age: 20,
      bust: 95,
      waist: 80,
      hips: 95,
      height: 182,
      weight: 75,
      hairLength: 'Короткие',
      hairType: 'Волнистые',
      hairstyle: 'Распущенные',
      hairColor: 'Брюнет',
      eyeColor: 'Карие',
      hasMakeup: false,
      eyelinerStyle: 'Нет',
      eyeshadowColor: 'Нет',
      lipstickColor: 'Нет',
      skinTone: 'Загорелая',
      ethnicity: 'Испанский',
      imageStyle: 'Гиперреалистичная фотография',
      physiqueDescription: '',
      bodyFat: 15,
      muscleMass: 'Тонизированная',
      breastShape: 'Круглая',
      breastFirmness: 'Упругая',
      buttockShape: 'Круглая',
      buttockFirmness: 'Упругая',
      headShape: 'Овальная',
      foreheadSize: 'Средний',
      eyebrowShape: 'Прямые',
      eyebrowThickness: 'Густые',
      eyeShape: 'Миндалевидные',
      eyeSize: 'Средние',
      eyeSpacing: 'Среднее расстояние',
      noseShape: 'Прямой',
      noseSize: 'Средний',
      lipShape: 'Полные',
      cheekbones: 'Низкие скулы',
      chinShape: 'Квадратный',
      clothingPreset: 'Студент университета',
      baseLayerType: 'Нет одежды',
      baseLayerColor: '',
      baseLayerMaterial: 'Обычная ткань',
      topType: 'Нет одежды',
      topColor: '',
      topMaterial: 'Обычная ткань',
      bottomType: 'Джинсы',
      bottomColor: 'Синий',
      bottomMaterial: 'Обычная ткань',
      outerwearType: 'Худи',
      outerwearColor: 'Серый',
      outerwearMaterial: 'Обычная ткань',
      footwearType: 'Кроссовки',
      footwearColor: 'Белый',
      footwearMaterial: 'Обычная ткань',
      accessories: [],
      accessoriesCustom: 'На худи логотип университета',
      hasAccessories: true,
      hasTattoos: false,
      tattooDescription: '',
    }
  },
  {
    name: 'Нуарный Детектив',
    profile: {
      gender: 'Мужской',
      age: 45,
      bust: 105,
      waist: 95,
      hips: 100,
      height: 178,
      weight: 88,
      hairLength: 'Короткие',
      hairType: 'Прямые',
      hairstyle: 'Распущенные',
      hairColor: 'Черный',
      eyeColor: 'Серые',
      hasMakeup: false,
      eyelinerStyle: 'Нет',
      eyeshadowColor: 'Нет',
      lipstickColor: 'Нет',
      skinTone: 'Оливковая',
      ethnicity: 'Европеоид',
      imageStyle: 'Фильм-нуар (высококонтрастный ч/б)',
      physiqueDescription: '',
      bodyFat: 25,
      muscleMass: 'Мягкая',
      breastShape: 'Круглая',
      breastFirmness: 'Упругая',
      buttockShape: 'Круглая',
      buttockFirmness: 'Упругая',
      headShape: 'Квадратная',
      foreheadSize: 'Высокий',
      eyebrowShape: 'Прямые',
      eyebrowThickness: 'Средние',
      eyeShape: 'Глубоко посаженные',
      eyeSize: 'Маленькие',
      eyeSpacing: 'Среднее расстояние',
      noseShape: 'Римский',
      noseSize: 'Большой',
      lipShape: 'Тонкие',
      cheekbones: 'Впалые щеки',
      chinShape: 'Квадратный',
      clothingPreset: 'Нуарный детектив',
      baseLayerType: 'Нет одежды',
      baseLayerColor: '',
      baseLayerMaterial: 'Обычная ткань',
      topType: 'Рубашка на пуговицах',
      topColor: 'Белый',
      topMaterial: 'Обычная ткань',
      bottomType: 'Брюки',
      bottomColor: 'Темно-серый',
      bottomMaterial: 'Обычная ткань',
      outerwearType: 'Тренч',
      outerwearColor: 'Бежевый',
      outerwearMaterial: 'Обычная ткань',
      footwearType: 'Лоферы',
      footwearColor: 'Черный',
      footwearMaterial: 'Обычная ткань',
      accessories: ['Галстук'],
      accessoriesCustom: '',
      hasAccessories: true,
      hasTattoos: false,
      tattooDescription: '',
    }
  },
  {
    name: 'Алиса',
    profile: {
      gender: 'Женский',
      age: 21,
      bust: 100,
      waist: 60,
      hips: 108,
      height: 170,
      weight: 63,
      hairLength: 'Длинные',
      hairType: 'Волнистые',
      hairstyle: 'Распущенные',
      hairColor: 'Каштановый',
      eyeColor: 'Зеленые',
      hasMakeup: true,
      eyelinerStyle: 'Тонкая',
      eyeshadowColor: 'Розовое шампанское',
      lipstickColor: 'Глянцевый розовый',
      skinTone: 'Светлая',
      ethnicity: 'Европеоид',
      imageStyle: 'Гиперреалистичная фотография',
      physiqueDescription: '',
      bodyFat: 24,
      muscleMass: 'Тонизированная',
      breastShape: 'Круглая',
      breastFirmness: 'Упругая',
      buttockShape: 'А-образная (сердечко)',
      buttockFirmness: 'Упругая',
      headShape: 'Овальная',
      foreheadSize: 'Средний',
      eyebrowShape: 'Изогнутые',
      eyebrowThickness: 'Средние',
      eyeShape: 'Миндалевидные',
      eyeSize: 'Средние',
      eyeSpacing: 'Среднее расстояние',
      noseShape: 'Прямой',
      noseSize: 'Средний',
      lipShape: 'Полные',
      cheekbones: 'Высокие скулы',
      chinShape: 'Острый',
      clothingPreset: 'Школьная форма',
      baseLayerType: 'Гольфы',
      baseLayerColor: 'Белый',
      baseLayerMaterial: 'Обычная ткань',
      topType: 'Кроп-топ',
      topColor: 'Белый',
      topMaterial: 'Обычная ткань',
      bottomType: 'Юбка в клетку',
      bottomColor: 'Синяя клетка',
      bottomMaterial: 'Обычная ткань',
      outerwearType: 'Нет одежды',
      outerwearColor: '',
      outerwearMaterial: 'Обычная ткань',
      footwearType: 'Лоферы',
      footwearColor: 'Коричневый',
      footwearMaterial: 'Обычная ткань',
      accessories: ['Галстук'],
      accessoriesCustom: 'Школьный галстук',
      hasAccessories: true,
      hasTattoos: false,
      tattooDescription: '',
    }
  },
  {
    name: 'Лайвет',
    profile: {
      gender: 'Женский',
      age: 31,
      bust: 123,
      waist: 69,
      hips: 120,
      height: 175,
      weight: 73,
      hairLength: 'Длинные',
      hairType: 'Прямые',
      hairstyle: 'Распущенные с челкой',
      hairColor: 'Рыжий',
      eyeColor: 'Зеленые',
      hasMakeup: true,
      eyelinerStyle: 'Крылатая',
      eyeshadowColor: 'Мерцающее золото',
      lipstickColor: 'Натуральный',
      skinTone: 'Светлая',
      ethnicity: 'Европеоид',
      imageStyle: 'Гиперреалистичная фотография',
      physiqueDescription: '',
      bodyFat: 28,
      muscleMass: 'Мягкая',
      breastShape: 'Круглая',
      breastFirmness: 'Мягкая',
      buttockShape: 'Круглая',
      buttockFirmness: 'Мягкая',
      headShape: 'Сердцевидная',
      foreheadSize: 'Средний',
      eyebrowShape: 'С изломом',
      eyebrowThickness: 'Средние',
      eyeShape: 'Приподнятые уголки',
      eyeSize: 'Большие',
      eyeSpacing: 'Среднее расстояние',
      noseShape: 'Курносый',
      noseSize: 'Маленький',
      lipShape: 'С четким бантом Купидона',
      cheekbones: 'Высокие скулы',
      chinShape: 'Острый',
      clothingPreset: 'Свой',
      baseLayerType: 'Чулки до бедра',
      baseLayerColor: 'Черный',
      baseLayerMaterial: 'Обычная ткань',
      topType: 'Кроп-топ',
      topColor: 'Белый',
      topMaterial: 'Обычная ткань',
      bottomType: 'Мини-юбка',
      bottomColor: 'Черный',
      bottomMaterial: 'Обычная ткань',
      outerwearType: 'Кожаная куртка',
      outerwearColor: 'Черный',
      outerwearMaterial: 'Обычная ткань',
      footwearType: 'Туфли-лодочки (стилетто)',
      footwearColor: 'Темно-красный',
      footwearMaterial: 'Обычная ткань',
      accessories: ['Чокер'],
      accessoriesCustom: 'Черный чокер на шее',
      hasAccessories: true,
      hasTattoos: false,
      tattooDescription: '',
    }
  },
  {
    name: 'Ксения',
    profile: {
      gender: 'Женский',
      age: 24,
      bust: 92,
      waist: 64,
      hips: 98,
      height: 168,
      weight: 58,
      hairLength: 'Длинные',
      hairType: 'Волнистые',
      hairstyle: 'Распущенные',
      hairColor: 'Каштановый',
      eyeColor: 'Карие',
      hasMakeup: true,
      eyelinerStyle: 'Крылатая',
      eyeshadowColor: 'Нейтральный коричневый',
      lipstickColor: 'Натуральный',
      skinTone: 'Светлая',
      ethnicity: 'Европеоид',
      imageStyle: 'Гиперреалистичная фотография',
      physiqueDescription: '',
      bodyFat: 22,
      muscleMass: 'Тонизированная',
      breastShape: 'Каплевидная',
      breastFirmness: 'Упругая',
      buttockShape: 'Круглая',
      buttockFirmness: 'Упругая',
      headShape: 'Овальная',
      foreheadSize: 'Средний',
      eyebrowShape: 'Изогнутые',
      eyebrowThickness: 'Средние',
      eyeShape: 'Миндалевидные',
      eyeSize: 'Средние',
      eyeSpacing: 'Среднее расстояние',
      noseShape: 'Прямой',
      noseSize: 'Средний',
      lipShape: 'Полные',
      cheekbones: 'Высокие скулы',
      chinShape: 'Острый',
      clothingPreset: 'Свой',
      baseLayerType: 'Гольфы',
      baseLayerColor: 'Белый',
      baseLayerMaterial: 'Обычная ткань',
      topType: 'Нет одежды',
      topColor: '',
      topMaterial: 'Обычная ткань',
      bottomType: 'Нет одежды',
      bottomColor: '',
      bottomMaterial: 'Обычная ткань',
      outerwearType: 'Нет одежды',
      outerwearColor: '',
      outerwearMaterial: 'Обычная ткань',
      footwearType: 'Высокие каблуки',
      footwearColor: 'Черный',
      footwearMaterial: 'Обычная ткань',
      accessories: ['Ожерелье'],
      accessoriesCustom: 'Облегающее черное платье с длинными рукавами и высоким разрезом на бедре. Серебряное ожерелье с кулоном в виде полумесяца. Белые гольфы с фиолетовыми полосками.',
      hasAccessories: true,
      hasTattoos: false,
      tattooDescription: '',
    }
  },
  {
    name: 'Дашка',
    profile: {
      gender: 'Женский',
      age: 38,
      bust: 92,
      waist: 77,
      hips: 98,
      height: 167,
      weight: 60,
      hairLength: 'Длинные',
      hairType: 'Волнистые',
      hairstyle: 'Распущенные',
      hairColor: 'Блонд',
      eyeColor: 'Карие',
      hasMakeup: true,
      eyelinerStyle: 'Тонкая',
      eyeshadowColor: 'Мерцающее золото',
      lipstickColor: 'Натуральный',
      skinTone: 'Светлая',
      ethnicity: 'Европеоид',
      imageStyle: 'Гиперреалистичная фотография',
      physiqueDescription: '',
      bodyFat: 25,
      muscleMass: 'Тонизированная',
      breastShape: 'Каплевидная',
      breastFirmness: 'Естественная',
      buttockShape: 'А-образная (сердечко)',
      buttockFirmness: 'Естественная',
      headShape: 'Овальная',
      foreheadSize: 'Средний',
      eyebrowShape: 'Изогнутые',
      eyebrowThickness: 'Средние',
      eyeShape: 'Миндалевидные',
      eyeSize: 'Средние',
      eyeSpacing: 'Среднее расстояние',
      noseShape: 'Прямой',
      noseSize: 'Средний',
      lipShape: 'Полные',
      cheekbones: 'Высокие скулы',
      chinShape: 'Острый',
      clothingPreset: 'Летний кэжуал',
      baseLayerType: 'Нет одежды',
      baseLayerColor: '',
      baseLayerMaterial: 'Обычная ткань',
      topType: 'Майка',
      topColor: 'Желтый',
      topMaterial: 'Обычная ткань',
      bottomType: 'Шорты',
      bottomColor: 'Хаки',
      bottomMaterial: 'Обычная ткань',
      outerwearType: 'Нет одежды',
      outerwearColor: '',
      outerwearMaterial: 'Обычная ткань',
      footwearType: 'Сандалии',
      footwearColor: 'Коричневый',
      footwearMaterial: 'Обычная ткань',
      accessories: ['Солнечные очки'],
      accessoriesCustom: '',
      hasAccessories: true,
      hasTattoos: false,
      tattooDescription: '',
    }
  },
  {
    name: 'Александр',
    profile: {
      gender: 'Мужской',
      age: 36,
      bust: 115,
      waist: 95,
      hips: 105,
      height: 195,
      weight: 104,
      hairLength: 'Короткие',
      hairType: 'Прямые',
      hairstyle: 'Распущенные',
      hairColor: 'Светло-русый',
      eyeColor: 'Голубо-зеленые',
      hasMakeup: false,
      eyelinerStyle: 'Нет',
      eyeshadowColor: 'Нет',
      lipstickColor: 'Нет',
      skinTone: 'Светлая',
      ethnicity: 'Европеоид',
      imageStyle: 'Гиперреалистичная фотография',
      physiqueDescription: '',
      bodyFat: 22,
      muscleMass: 'Мускулистая',
      breastShape: 'Круглая',
      breastFirmness: 'Упругая',
      buttockShape: 'Круглая',
      buttockFirmness: 'Упругая',
      headShape: 'Овальная',
      foreheadSize: 'Средний',
      eyebrowShape: 'Прямые',
      eyebrowThickness: 'Средние',
      eyeShape: 'Миндалевидные',
      eyeSize: 'Средние',
      eyeSpacing: 'Среднее расстояние',
      noseShape: 'Прямой',
      noseSize: 'Средний',
      lipShape: 'Тонкие',
      cheekbones: 'Высокие скулы',
      chinShape: 'Квадратный',
      clothingPreset: 'Свой',
      baseLayerType: 'Нет одежды',
      baseLayerColor: '',
      baseLayerMaterial: 'Обычная ткань',
      topType: 'Рубашка на пуговицах',
      topColor: 'Черный',
      topMaterial: 'Обычная ткань',
      bottomType: 'Брюки (классические)',
      bottomColor: 'Серый',
      bottomMaterial: 'Обычная ткань',
      outerwearType: 'Нет одежды',
      outerwearColor: '',
      outerwearMaterial: 'Обычная ткань',
      footwearType: 'Лоферы',
      footwearColor: 'Черный',
      footwearMaterial: 'Обычная ткань',
      accessories: ['Часы'],
      accessoriesCustom: 'Черные наручные часы на левом запястье.',
      hasAccessories: true,
      hasTattoos: false,
      tattooDescription: '',
    }
  },
  {
    name: 'Celesta',
    profile: {
      gender: 'Женский',
      age: 23,
      bust: 95,
      waist: 65,
      hips: 100,
      height: 168,
      weight: 62,
      hairLength: 'Длинные',
      hairType: 'Волнистые',
      hairstyle: 'Распущенные',
      hairColor: 'Брюнет',
      eyeColor: 'Голубо-зеленые',
      hasMakeup: true,
      eyelinerStyle: 'Тонкая',
      eyeshadowColor: 'Розовое шампанское',
      lipstickColor: 'Глянцевый розовый',
      skinTone: 'Светлая',
      ethnicity: 'Европеоид',
      imageStyle: 'Гиперреалистичная фотография',
      physiqueDescription: '',
      bodyFat: 21,
      muscleMass: 'Тонизированная',
      breastShape: 'Круглая',
      breastFirmness: 'Подтянутая',
      buttockShape: 'Круглая',
      buttockFirmness: 'Упругая',
      headShape: 'Овальная',
      foreheadSize: 'Средний',
      eyebrowShape: 'Изогнутые',
      eyebrowThickness: 'Средние',
      eyeShape: 'Миндалевидные',
      eyeSize: 'Большие',
      eyeSpacing: 'Среднее расстояние',
      noseShape: 'Прямой',
      noseSize: 'Средний',
      lipShape: 'Полные',
      cheekbones: 'Высокие скулы',
      chinShape: 'Острый',
      clothingPreset: 'Платье-комбинация в стиле 90-х',
      baseLayerType: 'Нет одежды',
      baseLayerColor: '',
      baseLayerMaterial: 'Обычная ткань',
      topType: 'Футболка (классическая)',
      topColor: 'Белый',
      topMaterial: 'Обычная ткань',
      bottomType: 'Нет одежды',
      bottomColor: '',
      bottomMaterial: 'Обычная ткань',
      outerwearType: 'Нет одежды',
      outerwearColor: '',
      outerwearMaterial: 'Обычная ткань',
      footwearType: 'Ботинки-комбат',
      footwearColor: 'Черный',
      footwearMaterial: 'Обычная ткань',
      accessories: ['Чокер'],
      accessoriesCustom: 'Черное шелковое платье-комбинация (slip dress) надето поверх белой футболки, чокер на шее',
      hasAccessories: true,
      hasTattoos: false,
      tattooDescription: '',
    }
  },
  {
    name: 'Lain',
    profile: {
      gender: 'Женский',
      age: 23,
      bust: 105,
      waist: 65,
      hips: 110,
      height: 168,
      weight: 65,
      hairLength: 'Длинные',
      hairType: 'Прямые',
      hairstyle: 'Распущенные',
      hairColor: 'Брюнет',
      eyeColor: 'Карие',
      hasMakeup: true,
      eyelinerStyle: 'Тонкая',
      eyeshadowColor: 'Нейтральный коричневый',
      lipstickColor: 'Натуральный',
      skinTone: 'Светлая',
      ethnicity: 'Европеоид',
      imageStyle: 'Гиперреалистичная фотография',
      physiqueDescription: '',
      bodyFat: 26,
      muscleMass: 'Тонизированная',
      breastShape: 'Круглая',
      breastFirmness: 'Естественная',
      buttockShape: 'Круглая',
      buttockFirmness: 'Естественная',
      headShape: 'Овальная',
      foreheadSize: 'Средний',
      eyebrowShape: 'Изогнутые',
      eyebrowThickness: 'Средние',
      eyeShape: 'Миндалевидные',
      eyeSize: 'Большие',
      eyeSpacing: 'Среднее расстояние',
      noseShape: 'Прямой',
      noseSize: 'Средний',
      lipShape: 'Полные',
      cheekbones: 'Высокие скулы',
      chinShape: 'Острый',
      clothingPreset: 'Черный облегающий комбинезон',
      baseLayerType: 'Нет одежды',
      baseLayerColor: '',
      baseLayerMaterial: 'Обычная ткань',
      topType: 'Нет одежды',
      topColor: '',
      topMaterial: 'Обычная ткань',
      bottomType: 'Нет одежды',
      bottomColor: '',
      bottomMaterial: 'Обычная ткань',
      outerwearType: 'Нет одежды',
      outerwearColor: '',
      outerwearMaterial: 'Обычная ткань',
      footwearType: 'Нет одежды',
      footwearColor: '',
      footwearMaterial: 'Обычная ткань',
      accessories: ['Очки в толстой оправе'],
      accessoriesCustom: 'Облегающий черный комбинезон с длинными рукавами, расстегнутый спереди, образуя глубокий V-образный вырез. На персонаже черные очки в толстой оправе.',
      hasAccessories: true,
      hasTattoos: true,
      tattooDescription: 'Персонаж имеет большую татуировку на грудине, которая видна в вырезе.',
    }
  },
  {
    name: 'Алина',
    profile: {
      gender: 'Женский',
      age: 22,
      bust: 90,
      waist: 65,
      hips: 95,
      height: 170,
      weight: 60,
      hairLength: 'До плеч',
      hairType: 'Волнистые',
      hairstyle: 'Распущенные',
      hairColor: 'Русый',
      eyeColor: 'Зеленые',
      hasMakeup: true,
      eyelinerStyle: 'Тонкая',
      eyeshadowColor: 'Нет',
      lipstickColor: 'Натуральный',
      skinTone: 'Светлая',
      ethnicity: 'Европеоид',
      imageStyle: 'Гиперреалистичная фотография',
      physiqueDescription: '',
      bodyFat: 22,
      muscleMass: 'Тонизированная',
      breastShape: 'Круглая',
      breastFirmness: 'Упругая',
      buttockShape: 'Круглая',
      buttockFirmness: 'Упругая',
      headShape: 'Овальная',
      foreheadSize: 'Средний',
      eyebrowShape: 'Изогнутые',
      eyebrowThickness: 'Средние',
      eyeShape: 'Миндалевидные',
      eyeSize: 'Средние',
      eyeSpacing: 'Среднее расстояние',
      noseShape: 'Прямой',
      noseSize: 'Маленький',
      lipShape: 'Полные',
      cheekbones: 'Высокие скулы',
      chinShape: 'Острый',
      clothingPreset: 'Чирлидер (Красный)',
      baseLayerType: 'Нет одежды',
      baseLayerColor: '',
      baseLayerMaterial: 'Обычная ткань',
      topType: 'Кроп-топ',
      topColor: 'Красный',
      topMaterial: 'Хлопок',
      bottomType: 'Плиссированная юбка',
      bottomColor: 'Красный',
      bottomMaterial: 'Обычная ткань',
      outerwearType: 'Нет одежды',
      outerwearColor: '',
      outerwearMaterial: 'Обычная ткань',
      footwearType: 'Кроссовки',
      footwearColor: 'Белый',
      footwearMaterial: 'Обычная ткань',
      accessories: [],
      accessoriesCustom: '',
      hasAccessories: false,
      hasTattoos: false,
      tattooDescription: '',
    }
  },
  {
    name: 'Victoria June',
    profile: {
      gender: 'Женский',
      age: 33,
      bust: 94,
      waist: 66,
      hips: 118,
      height: 161,
      weight: 60,
      hairLength: 'До плеч',
      hairType: 'Прямые',
      hairstyle: 'Каре',
      hairColor: 'Брюнет',
      eyeColor: 'Карие',
      hasMakeup: true,
      eyelinerStyle: 'Крылатая',
      eyeshadowColor: 'Нейтральный коричневый',
      lipstickColor: 'Матовый нюд',
      skinTone: 'Загорелая',
      ethnicity: 'Испанский',
      imageStyle: 'Гиперреалистичная фотография',
      physiqueDescription: '',
      bodyFat: 24,
      muscleMass: 'Атлетическая',
      breastShape: 'Каплевидная',
      breastFirmness: 'Подтянутая',
      buttockShape: 'Круглая',
      buttockFirmness: 'Тонизированная',
      headShape: 'Овальная',
      foreheadSize: 'Средний',
      eyebrowShape: 'Изогнутые',
      eyebrowThickness: 'Средние',
      eyeShape: 'Миндалевидные',
      eyeSize: 'Средние',
      eyeSpacing: 'Среднее расстояние',
      noseShape: 'Прямой',
      noseSize: 'Средний',
      lipShape: 'Полные',
      cheekbones: 'Высокие скулы',
      chinShape: 'Острый',
      clothingPreset: 'Черное латексное платье',
      baseLayerType: 'Нет одежды',
      baseLayerColor: '',
      baseLayerMaterial: 'Обычная ткань',
      topType: 'Нет одежды',
      topColor: '',
      topMaterial: 'Обычная ткань',
      bottomType: 'Нет одежды',
      bottomColor: '',
      bottomMaterial: 'Обычная ткань',
      outerwearType: 'Нет одежды',
      outerwearColor: '',
      outerwearMaterial: 'Обычная ткань',
      footwearType: 'Туфли-лодочки (стилетто)',
      footwearColor: 'Темно-красный',
      footwearMaterial: 'Глянцевый',
      accessories: ['Футуристичные солнечные очки'],
      accessoriesCustom: 'Облегающее черное мини-платье без рукавов из глянцевого латекса/винила с высоким воротником.',
      hasAccessories: true,
      hasTattoos: true,
      tattooDescription: 'Имя "XENA" написано на правом предплечье.',
    }
  }
];