import type { CatalogOption } from '../core';

export const BASE_LAYER_TYPES = [
  { id: "none", label: "Нет одежды" },
  { id: "classic_bra", label: "Бюстгальтер (классический)" },
  { id: "bralette", label: "Бралетт" },
  { id: "bandeau", label: "Бандо" },
  { id: "push_up_bra", label: "Бюстгальтер пуш-ап" },
  { id: "classic_panties", label: "Трусики (классические)" },
  { id: "thong", label: "Стринги" },
  { id: "boyshorts", label: "Бойшорты" },
  { id: "boxers", label: "Боксеры" },
  { id: "lace_lingerie_set", label: "Комплект белья (кружевной)" },
  { id: "corset", label: "Корсет" },
  { id: "waist_corset", label: "Корсет-пояс" },
  { id: "bodysuit", label: "Боди" },
  { id: "thigh_high_stockings", label: "Чулки до бедра" },
  { id: "tights", label: "Колготки" },
  { id: "knee_high_socks", label: "Гольфы" },
  { id: "socks", label: "Носки" },
  { id: "leotard", label: "Купальник-леотард" },
  { id: "one_piece_swimsuit", label: "Купальник (слитный)" },
] as const satisfies readonly CatalogOption[];
export type BaseLayerTypeId = typeof BASE_LAYER_TYPES[number]['id'];

export const TOP_TYPES = [
  { id: "none", label: "Нет одежды" },
  { id: "classic_t_shirt", label: "Футболка (классическая)" },
  { id: "v_neck_t_shirt", label: "Футболка (V-вырез)" },
  { id: "tank_top", label: "Майка" },
  { id: "crop_top", label: "Кроп-топ" },
  { id: "halter_top", label: "Халтер" },
  { id: "sports_bra", label: "Спортивный бюстгальтер" },
  { id: "rash_guard", label: "Рашгард" },
  { id: "classic_blouse", label: "Блузка (классическая)" },
  { id: "bow_blouse", label: "Блузка с бантом" },
  { id: "off_shoulder_top", label: "Топ с открытыми плечами (Бардо)" },
  { id: "button_up_shirt", label: "Рубашка на пуговицах" },
  { id: "corset_top", label: "Топ-корсет" },
  { id: "tunic", label: "Туника" },
  { id: "sweater", label: "Свитер" },
  { id: "pullover", label: "Пуловер" },
  { id: "turtleneck", label: "Водолазка" },
  { id: "cardigan", label: "Кардиган" },
  { id: "hoodie", label: "Худи" },
  { id: "sweatshirt", label: "Свитшот" },
  { id: "zip_hoodie", label: "Худи на молнии" },
  { id: "knitted_vest", label: "Трикотажный жилет" },
  { id: "suit_vest", label: "Пиджачный жилет" },
  { id: "medical_top", label: "Медицинский топ" },
  { id: "police_uniform_shirt", label: "Полицейская форма (рубашка)" },
  { id: "laboratory_coat", label: "Лабораторный халат" },
  { id: "bikini_top", label: "Верх от бикини" },
] as const satisfies readonly CatalogOption[];
export type TopTypeId = typeof TOP_TYPES[number]['id'];

export const BOTTOM_TYPES = [
  { id: "none", label: "Нет одежды" },
  { id: "skinny_jeans", label: "Джинсы (скинни)" },
  { id: "straight_jeans", label: "Джинсы (прямые)" },
  { id: "classic_trousers", label: "Брюки (классические)" },
  { id: "palazzo_trousers", label: "Широкие брюки (палаццо)" },
  { id: "cargo_trousers", label: "Брюки-карго" },
  { id: "chinos", label: "Чиносы" },
  { id: "leggings", label: "Леггинсы" },
  { id: "joggers", label: "Джоггеры" },
  { id: "pencil_skirt", label: "Юбка-карандаш" },
  { id: "mini_skirt", label: "Мини-юбка" },
  { id: "pleated_skirt", label: "Плиссированная юбка" },
  { id: "a_line_skirt", label: "Юбка А-силуэта" },
  { id: "plaid_skirt", label: "Юбка в клетку" },
  { id: "maxi_skirt", label: "Юбка-макси" },
  { id: "classic_shorts", label: "Шорты (классические)" },
  { id: "bermuda_shorts", label: "Шорты-бермуды" },
  { id: "cycling_shorts", label: "Велосипедки" },
  { id: "sport_shorts", label: "Спортивные шорты" },
  { id: "bikini_bottom", label: "Низ от бикини" },
  { id: "medical_trousers", label: "Медицинские брюки" },
  { id: "police_uniform_trousers", label: "Полицейская форма (брюки)" },
] as const satisfies readonly CatalogOption[];
export type BottomTypeId = typeof BOTTOM_TYPES[number]['id'];

export const OUTERWEAR_TYPES = [
  { id: "none", label: "Нет одежды" },
  { id: "bomber_jacket", label: "Куртка-бомбер" },
  { id: "leather_jacket", label: "Кожаная куртка" },
  { id: "denim_jacket", label: "Джинсовая куртка" },
  { id: "windbreaker", label: "Ветровка" },
  { id: "blazer", label: "Блейзер" },
  { id: "hoodie", label: "Худи" },
  { id: "trench_coat", label: "Тренч" },
  { id: "cloak", label: "Плащ" },
  { id: "coat", label: "Пальто" },
  { id: "oversized_coat", label: "Пальто-оверсайз" },
  { id: "puffer_jacket", label: "Пуховик" },
  { id: "parka", label: "Парка" },
  { id: "cape", label: "Кейп (пелерина)" },
  { id: "duffle_coat", label: "Дафлкот" },
  { id: "robe", label: "Халат" },
  { id: "apron", label: "Фартук" },
  { id: "laboratory_coat", label: "Лабораторный халат" },
  { id: "fur_wrap", label: "Меховая накидка" },
] as const satisfies readonly CatalogOption[];
export type OuterwearTypeId = typeof OUTERWEAR_TYPES[number]['id'];

export const FOOTWEAR_TYPES = [
  { id: "none", label: "Нет одежды" },
  { id: "sneakers", label: "Кроссовки" },
  { id: "high_top_sneakers", label: "Кеды (высокие)" },
  { id: "stiletto_pumps", label: "Туфли-лодочки (стилетто)" },
  { id: "block_heel_shoes", label: "Туфли на блочном каблуке" },
  { id: "high_heels", label: "Высокие каблуки" },
  { id: "platform_sandals", label: "Босоножки на платформе" },
  { id: "sandals", label: "Сандалии" },
  { id: "espadrilles", label: "Эспадрильи" },
  { id: "ballet_flats", label: "Балетки" },
  { id: "loafers", label: "Лоферы" },
  { id: "oxford_shoes", label: "Оксфорды" },
  { id: "moccasins", label: "Мокасины" },
  { id: "classic_boots", label: "Ботинки (классические)" },
  { id: "chelsea_boots", label: "Ботинки-челси" },
  { id: "combat_boots", label: "Ботинки-комбат" },
  { id: "knee_high_boots", label: "Сапоги до колена" },
  { id: "over_the_knee_boots", label: "Ботфорты" },
  { id: "riding_boots", label: "Сапоги для верховой езды" },
  { id: "pointe_shoes", label: "Пуанты" },
  { id: "ice_skates", label: "Коньки" },
  { id: "clogs", label: "Сабо" },
  { id: "swim_fins", label: "Ласты" },
] as const satisfies readonly CatalogOption[];
export type FootwearTypeId = typeof FOOTWEAR_TYPES[number]['id'];
