import type { CatalogCategory, CatalogOption } from '../core';

export const BACKGROUND_CATEGORIES = [
  { id: "studio_neutral", label: "Студия и нейтральные фоны" },
  { id: "interior", label: "Интерьеры" },
  { id: "nature", label: "Природа и открытые пространства" },
  { id: "urban", label: "Городские пространства" },
  { id: "fantasy_unique", label: "Необычные и фантастические пространства" },
] as const satisfies readonly CatalogCategory[];
export type BackgroundCategoryId = typeof BACKGROUND_CATEGORIES[number]['id'];

export const BACKGROUNDS = [
  { id: "professional_white_cyclorama", label: "Профессиональная фотостудия с белым фоном (циклорама)", categoryId: "studio_neutral" },
  { id: "minimal_gray_fabric_studio", label: "Минималистичная фотостудия с серым тканевым фоном", categoryId: "studio_neutral" },
  { id: "industrial_loft_studio", label: "Индустриальный лофт-студия с кирпичными стенами и большими окнами", categoryId: "studio_neutral" },
  { id: "neutral_white", label: "Нейтральный белый фон", categoryId: "studio_neutral" },
  { id: "neutral_gray", label: "Нейтральный серый фон", categoryId: "studio_neutral" },
  { id: "backstage_dressing_room", label: "Закулисная раздевалка с зеркалом в полный рост и вешалками для одежды", categoryId: "interior" },
  { id: "modern_bedroom_natural_light", label: "Уютная современная спальня с большим окном и естественным светом", categoryId: "interior" },
  { id: "modern_marble_kitchen", label: "Светлая современная кухня с мраморными столешницами", categoryId: "interior" },
  { id: "minimal_bathroom", label: "Минималистичная ванная комната с отдельно стоящей ванной и тропическим душем", categoryId: "interior" },
  { id: "library_with_fireplace", label: "Уютная библиотека с камином и книжными полками до потолка", categoryId: "interior" },
  { id: "ornate_ballroom", label: "Большой богато украшенный бальный зал с хрустальными люстрами", categoryId: "interior" },
  { id: "dark_neon_nightclub", label: "Темный переполненный ночной клуб с неоновыми огнями", categoryId: "interior" },
  { id: "modern_office_city_view", label: "Современный офис с панорамными окнами с видом на город", categoryId: "interior" },
  { id: "luxury_yacht_interior", label: "Интерьер роскошной яхты в открытом море", categoryId: "interior" },
  { id: "tropical_beach_sunset", label: "Тропический пляж на закате с пальмами", categoryId: "nature" },
  { id: "wild_rocky_beach", label: "Дикий скалистый пляж со штормовыми волнами", categoryId: "nature" },
  { id: "beach_volleyball_court", label: "Солнечная площадка для пляжного волейбола с золотым песком и сеткой", categoryId: "nature" },
  { id: "turquoise_tropical_sea", label: "Спокойное кристально чистое бирюзовое море у тропического острова", categoryId: "nature" },
  { id: "rooftop_infinity_pool", label: "Роскошный бассейн-инфинити на крыше с видом на город", categoryId: "nature" },
  { id: "country_garden_lawn", label: "Идеально подстриженный зеленый газон в загородном саду", categoryId: "nature" },
  { id: "mountain_sunrise_valley_fog", label: "Величественный горный пейзаж на рассвете с туманом в долинах", categoryId: "nature" },
  { id: "sunlit_mystical_forest", label: "Залитый солнцем древний мистический лес", categoryId: "nature" },
  { id: "stormy_sea_cliff", label: "Драматичный штормовой утес с видом на бушующее море", categoryId: "nature" },
  { id: "minimal_japanese_garden", label: "Безмятежный минималистичный японский сад с прудом кои", categoryId: "nature" },
  { id: "wheat_field_golden_hour", label: "Пшеничное поле в золотой час перед закатом", categoryId: "nature" },
  { id: "tokyo_neon_rain_night", label: "Оживленная улица Токио ночью с неоновыми вывесками и дождем", categoryId: "urban" },
  { id: "rainy_city_street_night", label: "Мокрая от дождя городская улица ночью под светом фонарей", categoryId: "urban" },
  { id: "sunlit_modern_city_street", label: "Современная залитая солнцем городская улица с размытой городской жизнью", categoryId: "urban" },
  { id: "medieval_market", label: "Шумный средневековый рынок", categoryId: "urban" },
  { id: "foggy_1940s_city_street", label: "Туманная тускло освещенная городская улица в стиле 1940-х годов", categoryId: "urban" },
  { id: "abandoned_factory", label: "Заброшенный завод с пробивающимся сквозь разбитые окна светом", categoryId: "fantasy_unique" },
  { id: "post_apocalyptic_city_ruins", label: "Постапокалиптические руины города", categoryId: "fantasy_unique" },
  { id: "red_carpet_paparazzi", label: "Сцена на красной ковровой дорожке со вспышками папарацци", categoryId: "fantasy_unique" },
  { id: "futuristic_spaceship_cockpit", label: "Кабина пилота футуристического космического корабля с видом на звезды", categoryId: "fantasy_unique" },
  { id: "old_castle", label: "Старинный замок с гобеленами и каменными стенами", categoryId: "fantasy_unique" },
  { id: "steampunk_airship_interior", label: "Интерьер фантастического дирижабля в стиле стимпанк", categoryId: "fantasy_unique" },
  { id: "studio_with_runway", label: "Студия с подиумом", categoryId: "studio_neutral" },
  { id: "fashion_boutique", label: "Интерьер модного бутика", categoryId: "interior" },
  { id: "studio_with_mirrors_makeup_table", label: "Студия с зеркалами и туалетным столиком", categoryId: "studio_neutral" },
  { id: "luxury_hotel_or_castle", label: "Интерьер роскошного отеля или замка", categoryId: "interior" },
  { id: "cozy_bedroom_or_boudoir", label: "Уютная спальня или будуар с антикварной мебелью", categoryId: "interior" },
  { id: "forest_or_rocky_beach", label: "Природа, густой лес или скалистый пляж", categoryId: "nature" },
  { id: "graffiti_street", label: "Улица с граффити", categoryId: "urban" },
  { id: "antique_house_interior", label: "Интерьер антикварного дома", categoryId: "interior" },
  { id: "fairy_forest_or_castle_ruins", label: "Сказочный лес или руины замка", categoryId: "fantasy_unique" },
  { id: "modern_gym_or_stadium", label: "Современный тренажерный зал или стадион", categoryId: "urban" },
  { id: "bright_room_window_light", label: "Светлая комната с мягким светом от окна", categoryId: "interior" },
  { id: "park_or_wedding_hall", label: "Парк или свадебный зал", categoryId: "nature" },
  { id: "cozy_cafe_or_home", label: "Уютное кафе или домашняя обстановка", categoryId: "interior" },
  { id: "american_1950s_diner", label: "Американский дайнер 50-х или ретро-автомобиль", categoryId: "interior" },
  { id: "empty_white_space", label: "Пустое белое пространство", categoryId: "studio_neutral" },
  { id: "authentic_village_or_temple", label: "Аутентичная деревня или храм", categoryId: "fantasy_unique" },
  { id: "studio_with_art_projections", label: "Студия с арт-проекциями", categoryId: "studio_neutral" },
  { id: "retro_kitchen_or_garage", label: "Ретро-кухня или гараж в стиле 50-х", categoryId: "interior" },
  { id: "gothic_cemetery_or_dark_forest", label: "Готическое кладбище или темный лес", categoryId: "fantasy_unique" },
] as const satisfies readonly CatalogOption<string, BackgroundCategoryId>[];
export type BackgroundId = typeof BACKGROUNDS[number]['id'];
