import type { CatalogCategory, CatalogOption } from '../core';

export const POSE_CATEGORIES = [
  { id: "standing", label: "Стоя" },
  { id: "sitting", label: "Сидя" },
  { id: "kneeling", label: "На коленях" },
  { id: "lying", label: "Лежа" },
  { id: "movement", label: "Движение" },
  { id: "dance", label: "Танец и пластика" },
  { id: "sport", label: "Спорт" },
  { id: "portrait", label: "Портретные" },
  { id: "dramatic", label: "Драматические" },
  { id: "special", label: "Специальные" },
] as const satisfies readonly CatalogCategory[];
export type PoseCategoryId = typeof POSE_CATEGORIES[number]['id'];

export const POSES = [
  { id: "standing_neutral", label: "Стоя, нейтральная поза", categoryId: "standing" },
  { id: "sitting_on_chair", label: "Сидя на стуле", categoryId: "sitting" },
  { id: "sitting_floor_hugging_knees", label: "Сидя на полу, обняв колени", categoryId: "sitting" },
  { id: "leaning_against_wall", label: "Оперевшись о стену", categoryId: "standing" },
  { id: "walking_forward_confidently", label: "Уверенно идет вперед", categoryId: "movement" },
  { id: "running_motion_pose", label: "Бег, поза в движении", categoryId: "movement" },
  { id: "joyful_jump", label: "Прыжок в воздухе, радостное выражение", categoryId: "movement" },
  { id: "dancing_gracefully", label: "Изящно танцует", categoryId: "dance" },
  { id: "crouched_ready_for_action", label: "Присев, в готовности к действию", categoryId: "kneeling" },
  { id: "lying_on_back_in_grass", label: "Лежа на спине в траве", categoryId: "lying" },
  { id: "looking_over_shoulder_smile", label: "Смотрит через плечо с легкой улыбкой", categoryId: "standing" },
  { id: "hands_on_hips_power", label: "Руки на бедрах, властная поза", categoryId: "standing" },
  { id: "waving_at_camera", label: "Машет в камеру", categoryId: "standing" },
  { id: "leaning_forward_over_table", label: "Наклонившись вперед над столом", categoryId: "standing" },
  { id: "chair_crossed_legs_selfie", label: "Сидя на стуле, закинув ногу на ногу, делая селфи", categoryId: "sitting" },
  { id: "kneeling_hands_on_knees", label: "Стоя на коленях, руки на коленях", categoryId: "kneeling" },
  { id: "wall_one_leg_raised", label: "Стоя у стены, одна нога согнута и приподнята", categoryId: "standing" },
  { id: "bending_touching_ankle", label: "Наклонившись вперед, касаясь лодыжки", categoryId: "standing" },
  { id: "three_quarter_looking_back", label: "Стоя вполоборота, оглядываясь через плечо", categoryId: "standing" },
  { id: "sitting_on_ledge_crossed_legs", label: "Сидя на уступе, элегантно скрестив ноги", categoryId: "sitting" },
  { id: "back_to_camera_head_turned", label: "Стоя спиной, голова повернута через плечо", categoryId: "standing" },
  { id: "ballet_stretch_at_barre", label: "Выполняя балетное растяжение у станка", categoryId: "dance" },
  { id: "sitting_on_box_thoughtful", label: "Сидя на ящике, задумчиво скрестив ноги", categoryId: "sitting" },
  { id: "mirror_hands_on_hips", label: "Стоя у зеркала, руки на бедрах, взгляд через плечо", categoryId: "standing" },
  { id: "standing_camera_soft_smile", label: "Стоя, взгляд в камеру, легкая улыбка", categoryId: "standing" },
  { id: "dynamic_walk_or_turn", label: "Динамичная поза в движении, ходьба или поворот", categoryId: "movement" },
  { id: "static_focus_on_expression", label: "Статичная поза, акцент на мимику", categoryId: "portrait" },
  { id: "graceful_body_curves", label: "Грациозная поза с изгибами тела", categoryId: "dance" },
  { id: "relaxed_on_bed_or_sofa", label: "Расслабленная поза на кровати или диване", categoryId: "lying" },
  { id: "artistic_body_contours", label: "Художественная поза, подчеркивающая контуры тела", categoryId: "dance" },
  { id: "running_or_jumping_on_beach", label: "Бег или прыжок на пляже", categoryId: "movement" },
  { id: "candid_walking_drinking_coffee", label: "Candid-поза, идет по улице и пьет кофе", categoryId: "movement" },
  { id: "static_symmetric_retro", label: "Статичная симметричная поза в ретро-стиле", categoryId: "portrait" },
  { id: "dramatic_epic", label: "Драматичная эпическая поза", categoryId: "dramatic" },
  { id: "sport_exercise_motion", label: "Спортивная поза в движении, выполнение упражнения", categoryId: "sport" },
  { id: "gentle_hands_on_belly", label: "Нежная поза с руками на животе", categoryId: "portrait" },
  { id: "elegant_with_bouquet", label: "Элегантная поза с букетом", categoryId: "portrait" },
  { id: "natural_reading_book", label: "Повседневная естественная поза, читает книгу", categoryId: "portrait" },
  { id: "playful_1950s", label: "Веселая игривая поза в стиле 50-х", categoryId: "dramatic" },
  { id: "simple_symmetric", label: "Простая симметричная поза", categoryId: "standing" },
  { id: "traditional_cultural", label: "Традиционная поза, отражающая культуру", categoryId: "standing" },
  { id: "abstract_unusual", label: "Абстрактная необычная поза", categoryId: "special" },
  { id: "flirty_playful_pinup", label: "Кокетливая игривая поза в стиле пин-ап", categoryId: "dramatic" },
  { id: "dramatic_mysterious", label: "Драматичная загадочная поза", categoryId: "dramatic" },
  { id: "cheerleader_split_jump_pom_poms", label: "Прыжок в шпагате в воздухе, руки вытянуты с помпонами", categoryId: "sport" },
  { id: "cheerleader_group_toss_split", label: "Подброшена высоко в воздух группой чирлидеров, выполняя прыжок в шпагате", categoryId: "sport" },
] as const satisfies readonly CatalogOption<string, PoseCategoryId>[];
export type PoseId = typeof POSES[number]['id'];

export const MOTIONS = [
  { id: "walking_confidently", label: "Уверенно идет" },
  { id: "running", label: "Бежит" },
  { id: "sneaking", label: "Крадучись пробирается" },
  { id: "dancing_gracefully", label: "Грациозно танцует" },
  { id: "jumping_with_joy", label: "Прыгает от радости" },
  { id: "waving_goodbye", label: "Машет на прощание" },
  { id: "stretching_after_sleep", label: "Потягивается после сна" },
  { id: "sword_fighting", label: "Сражается на мечах" },
  { id: "casting_spell", label: "Колдует заклинание" },
  { id: "playing_guitar", label: "Играет на гитаре" },
  { id: "looking_through_binoculars", label: "Смотрит в бинокль" },
  { id: "taking_photo", label: "Фотографирует" },
  { id: "falling", label: "Падает" },
  { id: "stumbling", label: "Спотыкается" },
] as const satisfies readonly CatalogOption[];
export type MotionId = typeof MOTIONS[number]['id'];

export const EMOTION_CATEGORIES = [
  { id: "neutral", label: "Нейтральные" },
  { id: "positive", label: "Положительные" },
  { id: "sadness", label: "Грусть" },
  { id: "anger", label: "Гнев" },
  { id: "fear", label: "Страх" },
  { id: "surprise", label: "Удивление" },
  { id: "negative_social", label: "Негативные социальные" },
  { id: "confidence", label: "Уверенность и флирт" },
  { id: "physical", label: "Физическое состояние" },
] as const satisfies readonly CatalogCategory[];
export type EmotionCategoryId = typeof EMOTION_CATEGORIES[number]['id'];

export const EMOTIONS = [
  { id: "neutral", label: "Нейтральное", categoryId: "neutral" },
  { id: "happiness", label: "Счастье", categoryId: "positive" },
  { id: "joy", label: "Радость", categoryId: "positive" },
  { id: "delight", label: "Восторг", categoryId: "positive" },
  { id: "peacefulness", label: "Умиротворение", categoryId: "positive" },
  { id: "sadness", label: "Грусть", categoryId: "sadness" },
  { id: "sorrow", label: "Печаль", categoryId: "sadness" },
  { id: "longing", label: "Тоска", categoryId: "sadness" },
  { id: "anger", label: "Злость", categoryId: "anger" },
  { id: "rage", label: "Гнев", categoryId: "anger" },
  { id: "fury", label: "Ярость", categoryId: "anger" },
  { id: "irritation", label: "Раздражение", categoryId: "anger" },
  { id: "fear", label: "Страх", categoryId: "fear" },
  { id: "horror", label: "Ужас", categoryId: "fear" },
  { id: "anxiety", label: "Тревога", categoryId: "fear" },
  { id: "surprise", label: "Удивление", categoryId: "surprise" },
  { id: "astonishment", label: "Изумление", categoryId: "surprise" },
  { id: "shock", label: "Шок", categoryId: "surprise" },
  { id: "disgust", label: "Отвращение", categoryId: "negative_social" },
  { id: "contempt", label: "Презрение", categoryId: "negative_social" },
  { id: "thoughtful", label: "Задумчивость", categoryId: "neutral" },
  { id: "focused", label: "Сосредоточенность", categoryId: "neutral" },
  { id: "confidence", label: "Уверенность", categoryId: "confidence" },
  { id: "smugness", label: "Самодовольство", categoryId: "confidence" },
  { id: "flirtation", label: "Кокетливость", categoryId: "confidence" },
  { id: "seduction", label: "Соблазнение", categoryId: "confidence" },
  { id: "embarrassment", label: "Смущение", categoryId: "confidence" },
  { id: "shyness", label: "Застенчивость", categoryId: "confidence" },
  { id: "pain", label: "Боль", categoryId: "physical" },
  { id: "suffering", label: "Страдание", categoryId: "physical" },
  { id: "tiredness", label: "Усталость", categoryId: "physical" },
  { id: "bored", label: "Скука", categoryId: "neutral" },
] as const satisfies readonly CatalogOption<string, EmotionCategoryId>[];
export type EmotionId = typeof EMOTIONS[number]['id'];

export const CHARACTER_ORIENTATIONS = [
  { id: "front", label: "Лицом к камере" },
  { id: "front_three_quarter", label: "В три четверти к камере" },
  { id: "profile", label: "Профиль, боком" },
  { id: "back_three_quarter", label: "В три четверти со спины" },
  { id: "back", label: "Спиной к камере" },
] as const satisfies readonly CatalogOption[];
export type CharacterOrientationId = typeof CHARACTER_ORIENTATIONS[number]['id'];
