import type { FieldDefinition } from '../catalog/core';

export const CHARACTER_FIELDS = [
  { id: 'identity.genderId', label: 'Пол', control: 'select', catalogKey: 'character.genders', required: true },
  { id: 'identity.age', label: 'Возраст', control: 'number', numericParameterKey: 'character.age', required: true },
  { id: 'body.height', label: 'Рост', control: 'number', numericParameterKey: 'character.height', required: true },
  { id: 'body.weight', label: 'Вес', control: 'number', numericParameterKey: 'character.weight', required: true },
  { id: 'body.bust', label: 'Обхват груди', control: 'number', numericParameterKey: 'character.bust', required: true },
  { id: 'body.waist', label: 'Обхват талии', control: 'number', numericParameterKey: 'character.waist', required: true },
  { id: 'body.hips', label: 'Обхват бедер', control: 'number', numericParameterKey: 'character.hips', required: true },
  { id: 'body.bodyFat', label: 'Процент жира', control: 'number', numericParameterKey: 'character.bodyFat', required: true },
  { id: 'body.muscleMassId', label: 'Мышечная масса', control: 'select', catalogKey: 'character.muscleMass', required: true },
  { id: 'body.breastSizeId', label: 'Размер груди', control: 'select', catalogKey: 'character.breastSizes', visibleWhen: { fieldId: 'identity.genderId', operator: 'equals', value: 'female' } },
  { id: 'body.breastShapeId', label: 'Форма груди', control: 'select', catalogKey: 'character.breastShapes', visibleWhen: { fieldId: 'identity.genderId', operator: 'equals', value: 'female' } },
  { id: 'body.breastFirmnessId', label: 'Упругость груди', control: 'select', catalogKey: 'character.breastFirmness', visibleWhen: { fieldId: 'identity.genderId', operator: 'equals', value: 'female' } },
  { id: 'body.buttockShapeId', label: 'Форма ягодиц', control: 'select', catalogKey: 'character.buttockShapes', visibleWhen: { fieldId: 'identity.genderId', operator: 'equals', value: 'female' } },
  { id: 'body.buttockFirmnessId', label: 'Упругость ягодиц', control: 'select', catalogKey: 'character.buttockFirmness', visibleWhen: { fieldId: 'identity.genderId', operator: 'equals', value: 'female' } },
  { id: 'appearance.imageStyleId', label: 'Стиль изображения', control: 'select', catalogKey: 'shared.imageStyles', required: true, searchable: true },
  { id: 'appearance.ethnicityId', label: 'Этнический тип', control: 'select', catalogKey: 'character.ethnicities', required: true },
  { id: 'appearance.skinToneId', label: 'Тон кожи', control: 'select', catalogKey: 'character.skinTones', required: true },
  { id: 'appearance.skinDetails', label: 'Дополнительное описание кожи', control: 'textarea' },
  { id: 'appearance.eyeColorId', label: 'Цвет глаз', control: 'select', catalogKey: 'character.eyeColors', required: true },
  { id: 'appearance.hair.lengthId', label: 'Длина волос', control: 'select', catalogKey: 'character.hairLengths', required: true },
  { id: 'appearance.hair.typeId', label: 'Тип волос', control: 'select', catalogKey: 'character.hairTypes', required: true },
  { id: 'appearance.hair.hairstyleId', label: 'Прическа', control: 'select', catalogKey: 'character.hairstyles', required: true },
  { id: 'appearance.hair.colorId', label: 'Цвет волос', control: 'select', catalogKey: 'character.hairColors', required: true },
  { id: 'appearance.hair.details', label: 'Дополнительное описание волос', control: 'textarea' },
  { id: 'face.headShapeId', label: 'Форма головы', control: 'select', catalogKey: 'character.headShapes', required: true },
  { id: 'face.foreheadSizeId', label: 'Лоб', control: 'select', catalogKey: 'character.foreheadSizes', required: true },
  { id: 'face.eyebrowShapeId', label: 'Форма бровей', control: 'select', catalogKey: 'character.eyebrowShapes', required: true },
  { id: 'face.eyebrowThicknessId', label: 'Густота бровей', control: 'select', catalogKey: 'character.eyebrowThickness', required: true },
  { id: 'face.eyeShapeId', label: 'Форма глаз', control: 'select', catalogKey: 'character.eyeShapes', required: true },
  { id: 'face.eyeSizeId', label: 'Размер глаз', control: 'select', catalogKey: 'character.eyeSizes', required: true },
  { id: 'face.eyeSpacingId', label: 'Расстояние между глазами', control: 'select', catalogKey: 'character.eyeSpacing', required: true },
  { id: 'face.noseShapeId', label: 'Форма носа', control: 'select', catalogKey: 'character.noseShapes', required: true },
  { id: 'face.noseSizeId', label: 'Размер носа', control: 'select', catalogKey: 'character.noseSizes', required: true },
  { id: 'face.lipShapeId', label: 'Форма губ', control: 'select', catalogKey: 'character.lipShapes', required: true },
  { id: 'face.cheekboneTypeId', label: 'Скулы и щеки', control: 'select', catalogKey: 'character.cheekboneTypes', required: true },
  { id: 'face.chinShapeId', label: 'Форма подбородка', control: 'select', catalogKey: 'character.chinShapes', required: true },
  { id: 'makeup.enabled', label: 'Макияж', control: 'boolean' },
  { id: 'makeup.eyelinerStyleId', label: 'Подводка', control: 'select', catalogKey: 'character.eyelinerStyles', visibleWhen: { fieldId: 'makeup.enabled', operator: 'truthy' } },
  { id: 'makeup.eyeshadowColorId', label: 'Тени', control: 'select', catalogKey: 'character.eyeshadowColors', visibleWhen: { fieldId: 'makeup.enabled', operator: 'truthy' } },
  { id: 'makeup.lipstickColorId', label: 'Помада', control: 'select', catalogKey: 'character.lipstickColors', visibleWhen: { fieldId: 'makeup.enabled', operator: 'truthy' } },
  { id: 'makeup.details', label: 'Дополнительное описание макияжа', control: 'textarea', visibleWhen: { fieldId: 'makeup.enabled', operator: 'truthy' } },
  { id: 'tattoos.enabled', label: 'Татуировки', control: 'boolean' },
  { id: 'tattoos.description', label: 'Описание татуировок', control: 'textarea', placeholder: 'Маленькая роза на левом плече, дракон на всю спину', visibleWhen: { fieldId: 'tattoos.enabled', operator: 'truthy' } },
  { id: 'permanentFeatures', label: 'Постоянные особенности', control: 'textarea', placeholder: 'Шрамы, родинки и другие признаки, которые нужно сохранять между сценами' },
] as const satisfies readonly FieldDefinition[];

export const WARDROBE_FIELDS = [
  { id: 'baseLayer.typeId', label: 'Нижний слой', control: 'select', catalogKey: 'wardrobe.baseLayerTypes' },
  { id: 'baseLayer.colorId', label: 'Цвет нижнего слоя', control: 'select', catalogKey: 'wardrobe.colors', disabledWhen: { fieldId: 'baseLayer.typeId', operator: 'equals', value: 'none' } },
  { id: 'baseLayer.materialId', label: 'Материал нижнего слоя', control: 'select', catalogKey: 'wardrobe.materials', disabledWhen: { fieldId: 'baseLayer.typeId', operator: 'equals', value: 'none' } },
  { id: 'top.typeId', label: 'Верх', control: 'select', catalogKey: 'wardrobe.topTypes' },
  { id: 'top.colorId', label: 'Цвет верха', control: 'select', catalogKey: 'wardrobe.colors', disabledWhen: { fieldId: 'top.typeId', operator: 'equals', value: 'none' } },
  { id: 'top.materialId', label: 'Материал верха', control: 'select', catalogKey: 'wardrobe.materials', disabledWhen: { fieldId: 'top.typeId', operator: 'equals', value: 'none' } },
  { id: 'bottom.typeId', label: 'Низ', control: 'select', catalogKey: 'wardrobe.bottomTypes' },
  { id: 'bottom.colorId', label: 'Цвет низа', control: 'select', catalogKey: 'wardrobe.colors', disabledWhen: { fieldId: 'bottom.typeId', operator: 'equals', value: 'none' } },
  { id: 'bottom.materialId', label: 'Материал низа', control: 'select', catalogKey: 'wardrobe.materials', disabledWhen: { fieldId: 'bottom.typeId', operator: 'equals', value: 'none' } },
  { id: 'outerwear.typeId', label: 'Верхняя одежда', control: 'select', catalogKey: 'wardrobe.outerwearTypes' },
  { id: 'outerwear.colorId', label: 'Цвет верхней одежды', control: 'select', catalogKey: 'wardrobe.colors', disabledWhen: { fieldId: 'outerwear.typeId', operator: 'equals', value: 'none' } },
  { id: 'outerwear.materialId', label: 'Материал верхней одежды', control: 'select', catalogKey: 'wardrobe.materials', disabledWhen: { fieldId: 'outerwear.typeId', operator: 'equals', value: 'none' } },
  { id: 'footwear.typeId', label: 'Обувь', control: 'select', catalogKey: 'wardrobe.footwearTypes' },
  { id: 'footwear.colorId', label: 'Цвет обуви', control: 'select', catalogKey: 'wardrobe.colors', disabledWhen: { fieldId: 'footwear.typeId', operator: 'equals', value: 'none' } },
  { id: 'footwear.materialId', label: 'Материал обуви', control: 'select', catalogKey: 'wardrobe.materials', disabledWhen: { fieldId: 'footwear.typeId', operator: 'equals', value: 'none' } },
  { id: 'accessoryIds', label: 'Аксессуары', control: 'multi_select', catalogKey: 'wardrobe.accessories', multiple: true, searchable: true },
  { id: 'customDescription', label: 'Дополнительное описание', control: 'textarea' },
] as const satisfies readonly FieldDefinition[];

export const SCENE_FIELDS = [
  { id: 'character.mode', label: 'Режим действия', control: 'select', required: true },
  { id: 'character.poseId', label: 'Статичная поза', control: 'select', catalogKey: 'scene.poses', visibleWhen: { fieldId: 'character.mode', operator: 'equals', value: 'pose' }, searchable: true },
  { id: 'character.motionId', label: 'Движение', control: 'select', catalogKey: 'scene.motions', visibleWhen: { fieldId: 'character.mode', operator: 'equals', value: 'motion' }, searchable: true },
  { id: 'character.emotionId', label: 'Эмоция', control: 'select', catalogKey: 'scene.emotions', required: true, searchable: true },
  { id: 'character.orientationId', label: 'Положение персонажа', control: 'select', catalogKey: 'scene.orientations', required: true },
  { id: 'camera.verticalAngleId', label: 'Вертикальный угол камеры', control: 'select', catalogKey: 'scene.verticalCameraAngles', required: true },
  { id: 'camera.horizontalAngleId', label: 'Горизонтальное положение камеры', control: 'select', catalogKey: 'scene.horizontalCameraAngles', required: true },
  { id: 'camera.shotTypeId', label: 'Тип кадра', control: 'select', catalogKey: 'scene.shotTypes', required: true },
  { id: 'camera.aspectRatioId', label: 'Соотношение сторон', control: 'select', catalogKey: 'scene.aspectRatios', required: true },
  { id: 'environment.backgroundId', label: 'Фон', control: 'select', catalogKey: 'scene.backgrounds', searchable: true },
  { id: 'environment.customBackground', label: 'Произвольный фон', control: 'textarea', allowCustomValue: true },
  { id: 'style.imageStyleId', label: 'Стиль изображения', control: 'select', catalogKey: 'shared.imageStyles', required: true, searchable: true },
  { id: 'lighting.typeId', label: 'Тип освещения', control: 'select', catalogKey: 'scene.lightingTypes', required: true },
  { id: 'lighting.naturalTimeId', label: 'Время суток', control: 'select', catalogKey: 'scene.naturalLightTimes', visibleWhen: { fieldId: 'lighting.typeId', operator: 'equals', value: 'natural' } },
  { id: 'lighting.studioSetupId', label: 'Схема студийного света', control: 'select', catalogKey: 'scene.studioLightSetups', visibleWhen: { fieldId: 'lighting.typeId', operator: 'equals', value: 'studio' } },
  { id: 'lighting.mainLightColorId', label: 'Цвет основного света', control: 'select', catalogKey: 'scene.lightColors', visibleWhen: { fieldId: 'lighting.typeId', operator: 'equals', value: 'studio' } },
  { id: 'lighting.accentLightColorId', label: 'Цвет акцентного света', control: 'select', catalogKey: 'scene.lightColors', visibleWhen: { fieldId: 'lighting.typeId', operator: 'equals', value: 'studio' } },
  { id: 'lighting.colorTemperature', label: 'Цветовая температура', control: 'number', numericParameterKey: 'scene.colorTemperature', required: true },
  { id: 'style.filterId', label: 'Фильтр', control: 'select', catalogKey: 'scene.filters', required: true },
  { id: 'reference.image', label: 'Референс сцены', control: 'image' },
  { id: 'reference.useClothing', label: 'Использовать одежду с референса', control: 'boolean' },
  { id: 'reference.useExpression', label: 'Использовать выражение лица с референса', control: 'boolean' },
] as const satisfies readonly FieldDefinition[];
